/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    users: User;
    pages: Page;
    media: Media;
    'square-categories': SquareCategory;
    'square-items': SquareItem;
    'square-item-variations': SquareItemVariation;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    'square-categories': {
      items: 'square-items';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'square-categories': SquareCategoriesSelect<false> | SquareCategoriesSelect<true>;
    'square-items': SquareItemsSelect<false> | SquareItemsSelect<true>;
    'square-item-variations': SquareItemVariationsSelect<false> | SquareItemVariationsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  text?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Categories synchronized from Square.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "square-categories".
 */
export interface SquareCategory {
  id: string;
  squareId: string;
  name: string;
  updatedAt: string;
  display?: boolean | null;
  items?: {
    docs?: (string | SquareItem)[] | null;
    hasNextPage?: boolean | null;
  } | null;
}
/**
 * Items synchronized from Square.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "square-items".
 */
export interface SquareItem {
  id: string;
  squareId: string;
  squareCategoryId: string;
  name: string;
  variations?:
    | {
        squareId: string;
        name: string;
        ordinal: number;
        pricingType: string;
        priceMoney: {
          amount: number;
          currency: string;
        };
        images?:
          | {
              squareId?: string | null;
              url?: string | null;
              id?: string | null;
            }[]
          | null;
        measurementUnit?: {
          squareId?: string | null;
          type?: string | null;
          precision?: number | null;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  display?: boolean | null;
  category?: (string | null) | SquareCategory;
}
/**
 * Item variations synchronized from Square.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "square-item-variations".
 */
export interface SquareItemVariation {
  id: string;
  squareId: string;
  name: string;
  ordinal: number;
  pricingType: string;
  priceMoney: {
    amount: number;
    currency: string;
  };
  images?:
    | {
        squareId?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  measurementUnit?: {
    squareId?: string | null;
    type?: string | null;
    precision?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'square-categories';
        value: string | SquareCategory;
      } | null)
    | ({
        relationTo: 'square-items';
        value: string | SquareItem;
      } | null)
    | ({
        relationTo: 'square-item-variations';
        value: string | SquareItemVariation;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  text?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "square-categories_select".
 */
export interface SquareCategoriesSelect<T extends boolean = true> {
  squareId?: T;
  name?: T;
  updatedAt?: T;
  display?: T;
  items?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "square-items_select".
 */
export interface SquareItemsSelect<T extends boolean = true> {
  squareId?: T;
  squareCategoryId?: T;
  name?: T;
  variations?:
    | T
    | {
        squareId?: T;
        name?: T;
        ordinal?: T;
        pricingType?: T;
        priceMoney?:
          | T
          | {
              amount?: T;
              currency?: T;
            };
        images?:
          | T
          | {
              squareId?: T;
              url?: T;
              id?: T;
            };
        measurementUnit?:
          | T
          | {
              squareId?: T;
              type?: T;
              precision?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  display?: T;
  category?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "square-item-variations_select".
 */
export interface SquareItemVariationsSelect<T extends boolean = true> {
  squareId?: T;
  name?: T;
  ordinal?: T;
  pricingType?: T;
  priceMoney?:
    | T
    | {
        amount?: T;
        currency?: T;
      };
  images?:
    | T
    | {
        squareId?: T;
        url?: T;
        id?: T;
      };
  measurementUnit?:
    | T
    | {
        squareId?: T;
        type?: T;
        precision?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}